nginx:
    build: ./nginx
    ports:
        - 81:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app
    environment:
        APPLICATION_ENV: docker

app:
    image: php:5.6.30-fpm
    volumes:
        - ./etd/build:/var/www/html/etd
    command: "true"

mysql:
    image: mysql:latest
    volumes:
        - ./etd/src/resources/sql:/docker-entrypoint-initdb.d
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: default
        MYSQL_USER: user
        MYSQL_PASSWORD: secret

data:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
    command: "true"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8081:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
